Evaluator/RealTime/instant_fluctuations_evaluator.py
Evaluator/RealTime/orderbook_evaluator.py
Evaluator/Social/forum_evaluator.py
Evaluator/Social/news_evaluator.py
Evaluator/Social/stats_evaluator.py
Evaluator/Strategies/high_frequency_strategy_evaluator.py
Evaluator/Strategies/market_stability_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator.py
Evaluator/TA/momentum_evaluator.py
Evaluator/TA/trend_evaluator.py
Evaluator/Util/overall_state_analysis.py
Evaluator/Util/statistics_analysis.py
Evaluator/Util/text_analysis.py
Trading/Mode/daily_trading_mode.py
Trading/Mode/high_frequency_mode.py
Trading/Mode/simple_trading_mode.py
tests/Evaluator/TA/test_klinger_TA_evaluator.py
tests/Trading/Mode/test_daily_trading_mode_creator.py
tests/Trading/Mode/test_daily_trading_mode_decider.py
tests/Trading/Mode/test_high_frequency_trading_mode.py

Improve constants imports (Octobot PR)[https://github.com/Drakkar-Software/OctoBot/pull/467]

Improve constants imports

---

.travis.yml
octobot_config.json

Improve travis CI file

---

Evaluator/TA/StochasticRSIVolatilityEvaluator.json
Evaluator/TA/in_development_TA_evaluators.py
Evaluator/TA/volatility_evaluator.py

Very simple stochasticRSI evaluator, but customizable with its config file !
In combination with RSI on 1h & 1D

Add stochasticRSI very simple evaluator

---

tests/Evaluator/Strategies/test_dip_analyser_strategy_evaluator.py
tests/Evaluator/Strategies/test_full_mixed_strategies_evaluator.py
tests/Evaluator/Strategies/test_move_signals_strategy_evaluator.py
tests/Evaluator/Strategies/test_simple_mixed_strategies_evaluator.py

update after https://github.com/Drakkar-Software/OctoBot/pull/958
requires https://github.com/Drakkar-Software/OctoBot/pull/961

Update strategy tests after backtesting update

---

tests/Trading/Mode/test_daily_trading_mode_creator.py

as well as https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/82
update after Drakkar-Software/OctoBot#958
requires Drakkar-Software/OctoBot#961

#81 update daily trading mode creator tests

---

Backtesting/collectors/exchanges/exchange_history_collector.py
Services/__init__.py
Services/reddit_service.py
Services/telegram_service.py
Services/twitter_service.py
Services/web_service.py
Websockets/__init__.py
Websockets/feeds/__init__.py
Websockets/feeds/bitmex.pxd
Websockets/feeds/bitmex.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/91

Services migration

---

Backtesting/collectors/exchanges/exchange_history_collector.py
Services/__init__.py
Services/reddit_service.py
Services/service_feeds/__init__.py
Services/service_feeds/reddit_service_feed.py
Services/service_feeds/telegram_service_feed.py
Services/service_feeds/twitter_service_feed.py
Services/telegram_service.py
Services/twitter_service.py
Services/web_service.py
Websockets/__init__.py
Websockets/feeds/__init__.py
Websockets/feeds/bitmex.pxd
Websockets/feeds/bitmex.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/92

Service feeds migration

---

Interfaces/__init__.py
Interfaces/telegram_bot_interface.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/94

Telegram interface migration

---

Backtesting/collectors/exchanges/exchange_live_collector.py
Evaluator/TA/momentum_evaluator.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/61

[ExchangeId] Add exchange id support

---

Notifiers/__init__.py
Notifiers/telegram_notifier.py
Notifiers/twitter_notifier.py
Notifiers/web_notifier.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/93

Notifiers migration 

---

Evaluator/Strategies/mixed_strategies_evaluator.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/19

[Matrix] migrate matrix callback

---

Trading/Mode/daily_trading_mode.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/66

[DailyTradingMode] fix set_final_eval

---

Evaluator/Social/__init__.py
Evaluator/Social/config/RedditForumEvaluator.json
Evaluator/Social/config/RedditForumEvaluator_schema.json
Evaluator/Social/forum_evaluator.py
Evaluator/Util/__init__.py
Evaluator/Util/overall_state_analysis.py
Evaluator/Util/text_analysis.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/96
depends on Drakkar-Software/OctoBot-Evaluators#13

migrate Reddit social evaluator

---

Services/telegram_service.py

(forgotten file with service migration)

update telegram service

---

Evaluator/Strategies/mixed_strategies_evaluator.py
Trading/Mode/daily_trading_mode.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/18
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/70

[Evaluators] Add evaluator matrix_id 

---

Backtesting/collectors/exchanges/exchange_history_collector.pxd
Backtesting/collectors/exchanges/exchange_history_collector.py
Backtesting/collectors/exchanges/exchange_live_collector.py
Interfaces/web/models/backtesting.py
Interfaces/web/templates/backtesting.html
Interfaces/web/templates/config_tentacle.html
Interfaces/web/templates/data_collector.html

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/12
(1st one is an example of invalid file)

Update for web data collector

---

Backtesting/collectors/exchanges/exchange_history_collector.py
Backtesting/collectors/exchanges/exchange_live_collector.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/72

[Backtesting] Migrate to exchange builder

---

Interfaces/web/models/dashboard.py
Interfaces/web/static/js/common/candlesticks.js
Interfaces/web/static/js/components/market_status.js

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/80
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/81

use klines to complete candle graphs

---

Interfaces/web/advanced_templates/advanced_matrix.html

requires https://github.com/Drakkar-Software/OctoBot-Interfaces/pull/14

update matrix view

---

Services/telegram_service.py

default telegram workers (threads) is 4

use one telegram worker to reduce thread usage

---

Interfaces/web/__init__.py
Interfaces/web/controllers/backtesting.py
Interfaces/web/models/backtesting.py
Interfaces/web/static/js/common/backtesting_util.js
Interfaces/web/static/js/common/bot_connection.js
Interfaces/web/static/js/common/util.js
Interfaces/web/static/js/components/backtesting.js
Interfaces/web/static/js/components/config_tentacle.js
Interfaces/web/templates/layout.html
Interfaces/web/web_interface.py
Interfaces/web/websockets/__init__.py
Interfaces/web/websockets/abstract_websocket_namespace_notifier.py
Interfaces/web/websockets/backtesting.py
Interfaces/web/websockets/notifications.py

* no more memory leak on web browser due to infinite requests
* superior refresh rate
* instant notifications pushed on server side
* better CPU management on server and client side
* no more infinite thread creation on http request !

use websockets for notifications, errors and backtesting 

---

Trading/Mode/daily_trading_mode.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/57

[TradingMode] Adapted DailyTradingMode to multiple instances

---

Backtesting/__init__.py
Backtesting/converters/exchanges/__init__.pxd
Backtesting/converters/exchanges/__init__.py
Backtesting/converters/exchanges/legacy_data_converter.pxd
Backtesting/converters/exchanges/legacy_data_converter.py
Interfaces/web/models/backtesting.py

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/25

handle v3 data file conversion 

---

Interfaces/web/controllers/trading.py
Interfaces/web/models/trading.py
Trading/Mode/daily_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/93

update trading mode state display 

---

Interfaces/web/__init__.py
Interfaces/web/controllers/commands.py
Interfaces/web/controllers/dashboard.py
Interfaces/web/models/dashboard.py
Interfaces/web/static/css/style.css
Interfaces/web/static/js/common/candlesticks.js
Interfaces/web/static/js/common/cst.js
Interfaces/web/static/js/components/dashboard.js
Interfaces/web/static/js/components/market_status.js
Interfaces/web/templates/index.html
Interfaces/web/templates/layout.html
Interfaces/web/templates/macros/tables.html
Interfaces/web/templates/symbol_market_status.html
Interfaces/web/templates/trades.html
Interfaces/web/web_interface.py
Interfaces/web/websockets/__init__.py
Interfaces/web/websockets/abstract_websocket_namespace_notifier.py
Interfaces/web/websockets/backtesting.py
Interfaces/web/websockets/dashboard.py
Interfaces/web/websockets/notifications.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/93
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/95

[WebInterface] update profitability, trades and candlesticks with websocket

---

Interfaces/web/__init__.py
Interfaces/web/controllers/trading.py
Interfaces/web/models/backtesting.py
Interfaces/web/models/trading.py
Interfaces/web/static/js/common/backtesting_util.js
Interfaces/web/templates/portfolio.html
Trading/Mode/daily_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/19
requires https://github.com/Drakkar-Software/OctoBot-Notifications/pull/6
requires https://github.com/Drakkar-Software/OctoBot-Interfaces/pull/17

update for in run backtesting 

---

Interfaces/web/models/backtesting.py
Interfaces/web/static/js/components/backtesting.js
Interfaces/web/static/js/components/data_collector.js
Interfaces/web/templates/backtesting.html
Interfaces/web/templates/data_collector.html

from 0.05s to 0.017s using asyncio.gather to read 17 data file descriptions

Optimize data file handling 

---

Interfaces/web/models/configuration.py
Interfaces/web/models/strategy_optimizer.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/33

Remove evaluator API wildcard usage 

---

Backtesting/converters/exchanges/legacy_data_converter.py
Interfaces/telegram_bot_interface.py
Interfaces/web/models/backtesting.py
Interfaces/web/models/tentacles.py
Interfaces/web/web_interface.py
Interfaces/web/websockets/backtesting.py
Interfaces/web/websockets/dashboard.py
Interfaces/web/websockets/notifications.py
Services/service_feeds/reddit_service_feed.py
Services/service_feeds/twitter_service_feed.py
Trading/Mode/daily_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/19

update exception logger

---

Interfaces/web/advanced_controllers/strategy_optimizer.py
Interfaces/web/advanced_templates/advanced_strategy_optimizer.html
Interfaces/web/models/backtesting.py
Interfaces/web/models/strategy_optimizer.py
Interfaces/web/static/js/components/strategy_optimizer.js
Interfaces/web/websockets/__init__.py
Interfaces/web/websockets/strategy_optimizer.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1052
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/33

Strategy optimizer update 

---

Interfaces/web/__init__.py
Interfaces/web/models/dashboard.py
Interfaces/web/templates/macros/tables.html
Interfaces/web/web_interface.py
Interfaces/web/websockets/dashboard.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/109
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/110

improve order type display 

---

Interfaces/web/constants.py
Interfaces/web/models/configuration.py
Interfaces/web/templates/config.html

change currency list api to use api.coincap.io 

---

Interfaces/web_interface/advanced_templates/advanced_layout.html
Interfaces/web_interface/controllers/dashboard.py
Interfaces/web_interface/security.py
Interfaces/web_interface/static/js/common/candlesticks.js
Interfaces/web_interface/templates/community.html
Interfaces/web_interface/templates/footer.html
Interfaces/web_interface/templates/index.html
Interfaces/web_interface/templates/layout.html
Interfaces/web_interface/web_interface.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/151

Web interface security update 

---

Evaluator/RealTime/instant_fluctuations_evaluator/instant_fluctuations_evaluator.py
Evaluator/RealTime/price_refresher_evaluator/__init__.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1080

Real time evals update 

---

Evaluator/RealTime/instant_fluctuations_evaluator/instant_fluctuations_evaluator.py
Evaluator/Social/signal_evaluator/signal_evaluators.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/153

fix call argument and lint issue 

---

Trading/Mode/daily_trading_mode/daily_trading_mode.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/45

[DailyTradingMode] Update matrix calls

---

Evaluator/TA/momentum_evaluator/momentum_evaluator.py
Evaluator/TA/momentum_evaluator/tests/test_klinger_TA_evaluator.py
Evaluator/TA/trend_evaluator/trend_evaluator.py
Evaluator/TA/volatility_evaluator/volatility_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1108

update TA minimal data length

---

Interfaces/web_interface/models/backtesting.py
Interfaces/web_interface/models/configuration.py
Interfaces/web_interface/static/js/common/backtesting_util.js
Interfaces/web_interface/static/js/components/config_tentacle.js

requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/54
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/50

remove config from strategy requirement api 

---

Interfaces/web_interface/static/js/components/backtesting.js
Interfaces/web_interface/templates/layout.html

fix backtesting files selector 

---

Evaluator/Strategies/mixed_strategies_evaluator/mixed_strategies_evaluator.py
Evaluator/TA/momentum_evaluator/tests/test_macd_TA_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/48

Strategy update

---

.travis.yml

requires https://github.com/Drakkar-Software/OctoBot/pull/1125

use 0.4.0 octobot 

---

Interfaces/telegram_bot_interface/telegram_bot_interface.py
Interfaces/web_interface/web_interface.py
Notifiers/telegram_notifier/telegram_notifier.py
Notifiers/twitter_notifier/twitter_notifier.py
Notifiers/web_notifier/web_notifier.py
Services/Services_feeds/google_service_feed/google_service_feed.py
Services/Services_feeds/reddit_service_feed/reddit_service_feed.py
Services/Services_feeds/telegram_service_feed/telegram_service_feed.py
Services/Services_feeds/twitter_service_feed/twitter_service_feed.py

requires https://github.com/Drakkar-Software/OctoBot-Notifications/pull/16
requires https://github.com/Drakkar-Software/OctoBot-Interfaces/pull/33
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/24

Multiple services update 

---

README.md
appveyor.yml

requires https://github.com/Drakkar-Software/OctoBot/pull/1128

add appveyor CI

---

Interfaces/web_interface/websockets/dashboard.py

Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/57

Fix OctoBot Commons updates

---

.travis.yml
Interfaces/web_interface/websockets/dashboard.py

Depends on https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/196

Fix travis deploy

---

Services/Interfaces/web_interface/models/backtesting.py
Services/Interfaces/web_interface/models/strategy_optimizer.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_producer.py
Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py

require https://github.com/Drakkar-Software/OctoBot/pull/1144
require https://github.com/Drakkar-Software/OctoBot/pull/1146

update for backtesting migration

---

Services/Interfaces/web_interface/models/backtesting.py
Services/Interfaces/web_interface/models/configuration.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/32

Tentacles io update

---

Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_producer.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading_mode.py
Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/__init__.py
Trading/Mode/staggered_orders_trading_mode/config/StaggeredOrdersTradingMode.json
Trading/Mode/staggered_orders_trading_mode/config/StaggeredOrdersTradingMode_schema.json
Trading/Mode/staggered_orders_trading_mode/metadata.json
Trading/Mode/staggered_orders_trading_mode/resources/StaggeredOrdersTradingMode.md
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/tests/__init__.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/186
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/33
requires https://github.com/Drakkar-Software/OctoBot/pull/1157

migrate staggered orders trading mode

---

.travis.yml
Evaluator/Strategies/dip_analyser_strategy_evaluator/tests/test_dip_analyser_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/config/SimpleStrategyEvaluator.json
Evaluator/Strategies/mixed_strategies_evaluator/config/TechnicalAnalysisStrategyEvaluator.json
Evaluator/Strategies/mixed_strategies_evaluator/config/TechnicalAnalysisStrategyEvaluator_schema.json
Evaluator/Strategies/mixed_strategies_evaluator/mixed_strategies_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator/move_signals_strategy_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator/tests/test_move_signals_strategy_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/191

Tentacle strategies tests

---

Services/Interfaces/web_interface/controllers/tentacles.py
Services/Interfaces/web_interface/models/tentacles.py
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/tentacles.html

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/38

fix tentacles multiple display

---

Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/config.html

add sandboxed and enabled options in exchanges config

---

Services/Interfaces/web_interface/controllers/tentacles.py
Services/Interfaces/web_interface/models/tentacles.py
Services/Interfaces/web_interface/static/js/components/tentacles_configuration.js
Services/Interfaces/web_interface/templates/tentacle_packages.html

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/39

update tentacles packages management

---

Evaluator/Strategies/dip_analyser_strategy_evaluator/tests/test_dip_analyser_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator/tests/test_move_signals_strategy_evaluator.py
Services/Interfaces/web_interface/controllers/backtesting.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/backtesting.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/backtesting_util.js
Services/Interfaces/web_interface/static/js/components/backtesting.js
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/config.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/portfolio.html

includes:
https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/229
https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/228
https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/227
https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/224
https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/216

Multiple updates

---

.travis.yml
Services/Interfaces/web_interface/models/backtesting.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/230
requires https://github.com/Drakkar-Software/OctoBot/pull/1174

Handle backtesting startup error

---

Services/Interfaces/web_interface/web_interface.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/44

implement register_new_exchange_impl

---

Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/tests/test_browse_all_pages.py
Services/Interfaces/web_interface/web_interface.py
Services/Services_bases/web_service/web_service.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/45

Web interface improvements

---

Evaluator/Social/forum_evaluator/forum_evaluator.py
Evaluator/Social/news_evaluator/news_evaluator.py
Evaluator/Social/trends_evaluator/trends_evaluator.py
Evaluator/Strategies/dip_analyser_strategy_evaluator/tests/test_dip_analyser_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator/tests/test_move_signals_strategy_evaluator.py
Services/Interfaces/telegram_bot_interface/tests/test_bot_interface.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/models/interface_settings.py
Services/Interfaces/web_interface/models/strategy_optimizer.py
Services/Interfaces/web_interface/models/tentacles.py
Services/Interfaces/web_interface/templates/components/config/evaluator_card.html
Services/Interfaces/web_interface/tests/test_browse_all_pages.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/240
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/88

Remove advanced manager

---

.travis.yml
Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py
azure-pipelines.yml

requires https://github.com/Drakkar-Software/OctoBot/pull/1213

update order close method

---

Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
Evaluator/TA/momentum_evaluator/momentum_evaluator.py

will require https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/84 to work properly

fix RSI momentum evaluator

---

Services/Interfaces/web_interface/web_interface.py
Services/Services_bases/web_service/web_service.py

keeping session secret key is an attack vector

create new session id a each startup

---

Services/Interfaces/web_interface/static/js/common/custom_elements.js

add percent values to portfolio display

---

Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/candlesticks.js
Services/Interfaces/web_interface/static/js/common/common_handlers.js
Services/Interfaces/web_interface/templates/components/config/evaluator_card.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/macros/cards.html
Services/Interfaces/web_interface/templates/macros/starting_waiter.html
Services/Interfaces/web_interface/templates/macros/tables.html
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/templates/trading.html

Displayed when data are not yet ready to be displayed (instead of displaying nothing)

add starting waiter on web interface

---

Services/Interfaces/web_interface/models/dashboard.py
Services/Interfaces/web_interface/web_interface.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/250
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/242 (version)

subscribe on ohlcv channel to ensure graph display

---

Trading/Mode/arbitrage_trading_mode/__init__.py
Trading/Mode/arbitrage_trading_mode/arbitrage_container.py
Trading/Mode/arbitrage_trading_mode/arbitrage_trading_mode.py
Trading/Mode/arbitrage_trading_mode/config/ArbitrageTradingMode.json
Trading/Mode/arbitrage_trading_mode/config/ArbitrageTradingMode_schema.json
Trading/Mode/arbitrage_trading_mode/metadata.json
Trading/Mode/arbitrage_trading_mode/resources/ArbitrageTradingMode.md
Trading/Mode/arbitrage_trading_mode/tests/__init__.py
Trading/Mode/arbitrage_trading_mode/tests/test_arbitrage_container.py
Trading/Mode/arbitrage_trading_mode/tests/test_arbitrage_trading_mode_consumer.py
Trading/Mode/arbitrage_trading_mode/tests/test_arbitrage_trading_mode_producer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/243
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/244

Add arbitrage trading mode

---

Services/Interfaces/web_interface/web_interface.py

update web interface imports

---

Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/templates/footer.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/macros/cards.html

navbar and footer now shrink on small screens and use rem instead of px

Improve ui

---

Trading/Exchange/bitmex/__init__.py
Trading/Exchange/bitmex/bitmex.py
Trading/Exchange/bitmex/metadata.json
Trading/Exchange/bitmex/resources/bitmex.md
Trading/Exchange/bitmex/tests/__init__.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/262
Closes https://github.com/Drakkar-Software/OctoBot-Trading/issues/261

[Exchange] Add default bitmex

---

Trading/Exchange/binance/__init__.py
Trading/Exchange/binance/binance.py
Trading/Exchange/binance/metadata.json
Trading/Exchange/binance/resources/binance.md
Trading/Exchange/binance/tests/__init__.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/262
Closes https://github.com/Drakkar-Software/OctoBot/issues/1243
Fixes binance balance fetching recvWindow error

[Exchange] Add default binance

---

Trading/Exchange/kraken/__init__.py
Trading/Exchange/kraken/kraken.py
Trading/Exchange/kraken/metadata.json
Trading/Exchange/kraken/resources/kraken.md
Trading/Exchange/kraken/tests/__init__.py

Fixes https://github.com/Drakkar-Software/OctoBot-Trading/issues/269

[Exchange] Add default kraken

---

Services/Interfaces/web_interface/advanced_controllers/configuration.py
Services/Interfaces/web_interface/constants.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/static/js/common/cst.js
Services/Interfaces/web_interface/static/js/common/dom_updater.js
Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/components/config/evaluator_card.html
Services/Interfaces/web_interface/templates/components/config/tentacle_card.html
Services/Interfaces/web_interface/templates/config.html

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/46

handle all tentacles activation

---

Services/Interfaces/web_interface/models/configuration.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/269

Fix tentacle config display

---

Services/Interfaces/web_interface/controllers/medias.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/static/js/common/resources_rendering.js
Services/Interfaces/web_interface/static/js/common/util.js
Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/components/config/exchange_card.html

display exchange logos

---

Services/Interfaces/telegram_bot_interface/telegram_bot_interface.py
Services/Interfaces/web_interface/api/trading.py
Services/Interfaces/web_interface/static/js/components/portfolio.js
Services/Interfaces/web_interface/static/js/components/trading.js
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/templates/trading.html

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/56

handle portfolio refresh instead of real trader refresh

---

Services/Interfaces/web_interface/static/js/common/bot_connection.js
Services/Interfaces/web_interface/static/js/common/util.js
Services/Interfaces/web_interface/static/js/components/trading.js

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/278

Refresh orders table

---

Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/config.html

issues:
- exchange added without any default value change was not saved
- impossible to add + remove + re-add an element
- impossible to save a config value with a white space (was removed)

fix config edit issues

---

Backtesting/collectors/exchanges/exchange_history_collector/exchange_history_collector.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/344

[ExchangeManager] Refactor followup

---

azure-pipelines.yml

[CI] Add windows 32bits

---

Trading/Exchange/binanceus/__init__.py
Trading/Exchange/binanceus/binanceus_exchange.py
Trading/Exchange/binanceus/metadata.json
Trading/Exchange/binanceus/resources/BinanceUS.md
Trading/Exchange/binanceus/tests/__init__.py

fixes https://github.com/Drakkar-Software/OctoBot-Launcher/issues/55

add binanceus tentacle

---

Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py
Backtesting/collectors/exchanges/exchange_history_collector/tests/__init__.py
Backtesting/collectors/exchanges/exchange_history_collector/tests/test_history_collector.py

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/111
requires https://github.com/Drakkar-Software/OctoBot/pull/1400

Fix data collector

---

Services/Interfaces/web_interface/__init__.py
Services/Interfaces/web_interface/advanced_templates/advanced_evaluator_config.html
Services/Interfaces/web_interface/advanced_templates/advanced_layout.html
Services/Interfaces/web_interface/advanced_templates/advanced_strategy_optimizer.html
Services/Interfaces/web_interface/controllers/__init__.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/flask_util/__init__.py
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/flask_util/template_filters.py
Services/Interfaces/web_interface/static/js/common/cst.js
Services/Interfaces/web_interface/static/js/common/json_editor_settings.js
Services/Interfaces/web_interface/templates/404.html
Services/Interfaces/web_interface/templates/500.html
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/commands.html
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/config.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/data_collector.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/templates/symbol_market_status.html
Services/Interfaces/web_interface/templates/tentacle_packages.html
Services/Interfaces/web_interface/templates/tentacles.html
Services/Interfaces/web_interface/templates/terms.html
Services/Interfaces/web_interface/templates/trading.html

auto reload cached static files when something is static folder changes (ex: tentacles update)

Fix web interface cache issues

---

Services/Interfaces/web_interface/web.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/79 in octobot requirements
requires https://github.com/Drakkar-Software/OctoBot/pull/1415

WebInterface handle CORS origins

---

Services/Interfaces/web_interface/static/css/style.css

fix currency medium size cards content align

---

Services/Interfaces/web_interface/controllers/trading.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/templates/trading.html

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/433 in octobot req

add exchange overload alert

---

Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/dashboard.py
Services/Interfaces/web_interface/models/interface_settings.py

fix home page graph infinite loop on disabled watched symbol

fix watched market display issue with disabled pairs

---

Services/Interfaces/web_interface/advanced_templates/advanced_evaluator_config.html
Services/Interfaces/web_interface/advanced_templates/advanced_strategy_optimizer.html
Services/Interfaces/web_interface/controllers/__init__.py
Services/Interfaces/web_interface/controllers/octobot_help.py
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/commands.html
Services/Interfaces/web_interface/templates/config.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/login.html
Services/Interfaces/web_interface/templates/octobot_help.html
Services/Interfaces/web_interface/templates/tentacle_packages.html
Services/Interfaces/web_interface/templates/tentacles.html
Services/Services_bases/reddit_service/reddit.py
Services/Services_bases/telegram_service/telegram.py
Services/Services_bases/trading_view_service/trading_view.py
Services/Services_bases/twitter_service/twitter.py
Services/Services_bases/web_service/web.py
Services/Services_bases/webhook_service/webhook.py

Add help page

---

Services/Interfaces/web_interface/advanced_templates/advanced_layout.html
Services/Interfaces/web_interface/static/css/layout.css
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/required.js
Services/Interfaces/web_interface/templates/config.html
Services/Interfaces/web_interface/templates/footer.html
Services/Interfaces/web_interface/templates/layout.html

Sidebar in config

---

.github/workflows/main.yml
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/configuration.py
Trading/Mode/arbitrage_trading_mode/tests/__init__.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_producer.py
Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

migrate trading config keys into commons

---

Services/Interfaces/web_interface/templates/index.html

remove web interface warning

---

Services/Interfaces/web_interface/static/js/common/bot_connection.js
Services/Interfaces/web_interface/templates/layout.html

will work after https://github.com/Drakkar-Software/OctoBot/pull/1452 merge

use socketio 3.0.4

---

.github/workflows/main.yml

Depends on https://github.com/Drakkar-Software/OctoBot/pull/1464

[CI] Migrate to OctoBot-Tentacles-Manager uploaders

---

Evaluator/Social/signal_evaluator/resources/TelegramSignalEvaluator.md
README.md
Services/Interfaces/web_interface/advanced_templates/advanced_evaluator_config.html
Services/Interfaces/web_interface/advanced_templates/advanced_strategy_optimizer.html
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/templates/accounts.html
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/commands.html
Services/Interfaces/web_interface/templates/components/config/currency_card.html
Services/Interfaces/web_interface/templates/components/config/profile_tab.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/login.html
Services/Interfaces/web_interface/templates/macros/cards.html
Services/Interfaces/web_interface/templates/octobot_help.html
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/templates/profile.html
Services/Interfaces/web_interface/templates/tentacle_packages.html
Services/Interfaces/web_interface/templates/tentacles.html
Services/Services_bases/reddit_service/reddit.py
Services/Services_bases/telegram_service/telegram.py
Services/Services_bases/trading_view_service/trading_view.py
Services/Services_bases/twitter_service/twitter.py
Services/Services_bases/web_service/web.py
Services/Services_bases/webhook_service/webhook.py

replaces https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/350

use docs.octobot.online

---

Services/Interfaces/web_interface/static/css/style.css

fix hover color on buttons links

---

Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/456 into octobot's requirements

update for OctoBot-Trading 1.11.30

---

Services/Interfaces/web_interface/advanced_templates/advanced_evaluator_config.html
Services/Interfaces/web_interface/advanced_templates/advanced_strategy_optimizer.html
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/templates/500.html
Services/Interfaces/web_interface/templates/accounts.html
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/commands.html
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/components/config/profile_tab.html
Services/Interfaces/web_interface/templates/components/config/service_card.html
Services/Interfaces/web_interface/templates/components/config/trader_card.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/footer.html
Services/Interfaces/web_interface/templates/login.html
Services/Interfaces/web_interface/templates/octobot_help.html
Services/Interfaces/web_interface/templates/profile.html
Services/Interfaces/web_interface/templates/tentacle_packages.html
Services/Interfaces/web_interface/templates/tentacles.html
Services/Services_bases/telegram_service/telegram.py
Services/Services_bases/web_service/web.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1529
requires https://github.com/Drakkar-Software/OctoBot-Project-Website/pull/13

[WebInterface] Use OctoBot website

---

Trading/Exchange/coinbase_pro/coinbase_pro_exchange.py

also requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/457 to fully work on cbp

[Trading][CoinbasePro] fix get_closed_orders

---

Services/Interfaces/web_interface/static/js/components/portfolio.js
Services/Interfaces/web_interface/templates/404.html
Services/Interfaces/web_interface/templates/500.html
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/commands.html
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/community_login.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/data_collector.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/login.html
Services/Interfaces/web_interface/templates/logs.html
Services/Interfaces/web_interface/templates/macros/starting_waiter.html
Services/Interfaces/web_interface/templates/octobot_help.html
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/templates/symbol_market_status.html
Services/Interfaces/web_interface/templates/tentacle_packages.html
Services/Interfaces/web_interface/templates/tentacles.html
Services/Interfaces/web_interface/templates/terms.html
Services/Interfaces/web_interface/templates/trades.html
Services/Interfaces/web_interface/templates/trading.html

Improve web interface

---

Services/Interfaces/web_interface/static/js/common/cst.js
Services/Interfaces/web_interface/static/js/common/custom_elements.js
Services/Interfaces/web_interface/static/js/common/util.js
Services/Interfaces/web_interface/static/js/components/portfolio.js
Services/Interfaces/web_interface/templates/portfolio.html

desktop
mobile (>6 elements)
<6

[WebInterface] improve portfolio chart display

---

Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

[StaggeredOrders] improve setup error messages

---

Trading/Exchange/kraken/kraken_exchange.py

Fix issues discovered in https://github.com/Drakkar-Software/OctoBot-Trading/pull/464

[Trading][Exchanges][Kraken] Add get_order_book and get_symbol_prices support

---

Services/Interfaces/telegram_bot_interface/telegram_bot.py

[Telegram] fix error handler issue

---

Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py

uses https://github.com/Drakkar-Software/OctoBot-Trading/pull/473

[TradingModes] handle order cancel

---

Services/Interfaces/web_interface/controllers/__init__.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/flask_util/__init__.py
Services/Interfaces/web_interface/flask_util/file_services.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/logs.py
Services/Interfaces/web_interface/static/js/common/util.js
Services/Interfaces/web_interface/static/js/components/logs.js
Services/Interfaces/web_interface/static/js/components/profile_management.js
Services/Interfaces/web_interface/templates/logs.html
Services/Interfaces/web_interface/tests/test_browse_all_pages.py

[WebInterface] Add export logs

---

Trading/Exchange/bittrex/bittrex_exchange.py

[Trading][Exchanges][Bittrex] Fix fetch_ticker

---

Trading/Exchange/bitfinex/__init__.py
Trading/Exchange/bitfinex/bitfinex_exchange.py
Trading/Exchange/bitfinex/metadata.json
Trading/Exchange/bittrex/bittrex_exchange.py

Fixes from https://github.com/Drakkar-Software/OctoBot-Trading/pull/482 results.

[Trading][Exchanges] Add bitfinex

---

Trading/Exchange/crex24/__init__.py
Trading/Exchange/crex24/crex24_exchange.py
Trading/Exchange/crex24/metadata.json
Trading/Exchange/crex24/resources/crex24.md
Trading/Exchange/crex24/tests/__init__.py
Trading/Exchange/hitbtc/__init__.py
Trading/Exchange/hitbtc/hitbtc_exchange.py
Trading/Exchange/hitbtc/metadata.json
Trading/Exchange/hitbtc/resources/hitbtc.md
Trading/Exchange/hitbtc/tests/__init__.py
Trading/Exchange/okex/__init__.py
Trading/Exchange/okex/metadata.json
Trading/Exchange/okex/okex_exchange.py
Trading/Exchange/okex/resources/okex.md
Trading/Exchange/okex/tests/__init__.py

Precision fix for all and OHLCV fix for hitbtc

[Trading][Exchanges] Add hitbtc, okex and crex24

---

Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/templates/commands.html

Requires https://github.com/Drakkar-Software/OctoBot-Services/pull/90

[WebInterface] Add suggest feature button

---

Services/Interfaces/web_interface/controllers/octobot_authentication.py
Trading/Exchange/bitmax/bitmax_exchange.py

Add failed login ip to log.
ex : Useful for fail2ban

Add failed login ip to log

---

.github/workflows/main.yml

It also changes the tentacle upload url. (no change needed, environment variables has been updated)

[CI] Remove x86 arch

---

Services/Interfaces/web_interface/templates/commands.html
Services/Interfaces/web_interface/templates/footer.html

[WebInterface] Improve donations visibility

---

Services/Interfaces/web_interface/advanced_templates/advanced_layout.html
Services/Interfaces/web_interface/controllers/__init__.py
Services/Interfaces/web_interface/controllers/commands.py
Services/Interfaces/web_interface/templates/about.html
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/footer.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/terms.html

display selected tab in page title

Title in tabs

---

Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/static/js/common/util.js
Services/Interfaces/web_interface/static/js/components/navbar.js
Services/Interfaces/web_interface/templates/components/modals/trading_state_modal.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/macros/trading_state.html

[WebInterface] Add trading state change

---

Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/profiles.py

from https://feedback.octobot.online/posts/41/better-file-names-for-exported-profiles
ex:

[WebInterface] improve profile export name

---

.github/workflows/main.yml
Services/Interfaces/web_interface/api/__init__.py
Services/Interfaces/web_interface/api/metadata.py
Services/Interfaces/web_interface/controllers/commands.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/commands.py
Services/Interfaces/web_interface/models/tentacles.py
Services/Interfaces/web_interface/static/js/components/dashboard.js
Services/Interfaces/web_interface/templates/index.html

WIP
Related to https://feedback.octobot.online/posts/6/add-an-octobot-update-button-in-webinterface
Related to https://github.com/Drakkar-Software/OctoBot/pull/1626

[WebInterface] Add self update

---

Trading/Mode/grid_trading_mode/grid_trading.py
Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading in octobot dev branch

Handle decimals

---

Services/Services_bases/telegram_api_service/__init__.py
Services/Services_bases/telegram_api_service/metadata.json
Services/Services_bases/telegram_api_service/telegram_api.py
Services/Services_feeds/telegram_api_service_feed/__init__.py
Services/Services_feeds/telegram_api_service_feed/metadata.json
Services/Services_feeds/telegram_api_service_feed/telegram_api_feed.py

Related to https://github.com/Drakkar-Software/OctoBot-Services/pull/97

[Services] Add telegram API

---

Evaluator/Social/signal_evaluator/__init__.py
Evaluator/Social/signal_evaluator/config/TelegramChannelSignalEvaluator.json
Evaluator/Social/signal_evaluator/config/TelegramChannelSignalEvaluator_schema.json
Evaluator/Social/signal_evaluator/metadata.json
Evaluator/Social/signal_evaluator/resources/TelegramChannelSignalEvaluator.md
Evaluator/Social/signal_evaluator/signal.py
Evaluator/Social/signal_evaluator/tests/__init__.py
Evaluator/Social/signal_evaluator/tests/test_telegram_channel_signal_evaluator.py

Requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/434

[Evaluator][Social][Signal] Add pump and dump handler

---

Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/templates/tutorial.html

[WebInterface] darken tutorial images

---

Services/Interfaces/web_interface/templates/trading.html

[WebInterface] sort market status trading pairs

---

Services/Interfaces/web_interface/advanced_controllers/configuration.py
Services/Interfaces/web_interface/advanced_templates/advanced_evaluator_config.html
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/templates/components/config/profile_tab.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/macros/tentacles.html
Services/Interfaces/web_interface/templates/profile.html

[WebInterface] Add read only display for profile strategy

---

Services/Interfaces/web_interface/models/profiles.py

Bad practice when using it as a path on Linux.

[WebInterface] Remove space in profile duplicate name

---

Trading/Mode/daily_trading_mode/resources/DailyTradingMode.md

[DailyTradingMode] integrate video tutorial

---

Services/Interfaces/web_interface/static/js/components/backtesting.js

Reported and approved by @LabQi on telegram channel

[BacktestingDataTable] Fix refresh

---

Services/Interfaces/telegram_bot_interface/telegram_bot.py
Services/Interfaces/web_interface/web.py
Services/Services_bases/reddit_service/reddit.py
Services/Services_feeds/reddit_service_feed/reddit_feed.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1676

Fix stop and migrate to asyncpraw

---

Services/Interfaces/web_interface/templates/footer.html

[Interfaces][Web] Add youtube link in footer

---

Services/Interfaces/web_interface/advanced_templates/advanced_strategy_optimizer.html

prevents https://github.com/Drakkar-Software/OctoBot/issues/1701

[WebInterface] add strategy optimizer info

---

Services/Interfaces/web_interface/static/js/components/profile_management.js
Services/Interfaces/web_interface/templates/components/config/profile_tab.html
Services/Interfaces/web_interface/templates/profile.html

read only
not read-only (title and desc can be clicked and edited)

Improve profiles UX

---

Services/Interfaces/web_interface/models/trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/533 in octobot requirements

[WebInterface] add has_websocket info in trading data

---

Services/Interfaces/web_interface/templates/profile.html

[WebInterface] differentiate read_only profiles in profiles selector

---

Services/Interfaces/web_interface/models/backtesting.py
Services/Interfaces/web_interface/models/configuration.py

fixes 
https://github.com/Drakkar-Software/OctoBot/issues/1735

[WebInterface] fix errors on backtesting files diplay and currency fetch

---

Trading/Exchange/binance_websocket_feed/binance_websocket.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/563

[Trading][Exchanges][Binance] Add Trades and Ticker to supported feeds

---

Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/accounts.html
Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/profile.html

[WebInterface] add details on partner exchanges

---

.github/workflows/comment.yml
.github/workflows/main.yml
okteto-pipeline.yml
okteto-stack.yaml
okteto.yml

Requires https://github.com/Drakkar-Software/OctoBot/pull/1738 to replace clone of feature/add-okteto-deploy-button to dev

[CI] Add okteto deploy PR button

---

Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/templates/profile.html

thanks to @perziusval on telegram
like BTCUP, BTCDOWN....
can be added but it's not shown after a refresh

[WebInterface][Profile][Currencies] Add custom configured pair in select

---

Evaluator/Util/candles_util/__init__.py
Evaluator/Util/candles_util/candles_util.pxd
Evaluator/Util/candles_util/candles_util.py
Evaluator/Util/candles_util/metadata.json
Evaluator/Util/candles_util/tests/test_candles_util.py

Include HL2, HLC3, OHLC4 and HeikinAshi

[Evaluator][Util] Add CandlesUtil

---

Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py

OctoBot WebInterface will freeze with a large data (when data is saved to db) so the container will restart If it's is set to restart on fail

[DataCollector] Fix freeze on some container

---

.github/workflows/main.yml
Services/Interfaces/web_interface/controllers/community.py
Services/Interfaces/web_interface/controllers/community_authentication.py
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/about.html
Services/Interfaces/web_interface/templates/accounts.html
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/community_login.html
Services/Interfaces/web_interface/templates/components/community/tentacles_packages.html
Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/profile.html
Services/Interfaces/web_interface/tests/test_browse_all_pages.py

requires the OctoBot community website ! 🎉 
requires https://github.com/Drakkar-Software/OctoBot/pull/1767

[WebInterface] handle supporters

---

Trading/Exchange/binance_websocket_feed/binance_websocket.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/588

[BinanceWS] Add candle constructor param

---

Services/Interfaces/web_interface/models/backtesting.py
Services/Interfaces/web_interface/static/js/components/data_collector.js
Services/Interfaces/web_interface/templates/data_collector.html

https://feedback.octobot.online/posts/63/backtesting-of-multiple-pairs

[WebInterface][DataCollector] Multi symbol collect

---

Backtesting/collectors/exchanges/exchange_history_collector/tests/test_history_collector.py

contains https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/530

Test multi symbol collector

---

Services/Services_feeds/trading_view_service_feed/trading_view_feed.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

added:
ORDER_TYPE=MARKET       (/LIMIT)
PRICE=10000                      (optional)
VOLUME=0.004                  (optional)

improve trading view trading mode

---

Trading/Exchange/okex/okex_exchange.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/596 and https://github.com/Drakkar-Software/OctoBot-Trading/pull/599

[OKEx] Add sandbox mode

---

Trading/Exchange/huobi_websocket_feed/__init__.py
Trading/Exchange/huobi_websocket_feed/huobi_websocket.py
Trading/Exchange/huobi_websocket_feed/metadata.json
Trading/Exchange/huobi_websocket_feed/tests/__init__.py
Trading/Exchange/huobi_websocket_feed/tests/test_unauthenticated_mocked_feeds.py

Requires https://github.com/Drakkar-Software/trading-backend/pull/9

[CryptofeedWebsocket] Add Huobi

---

Trading/Exchange/okex/okex_exchange.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/601

[OKEx] Add get_sub_account_list implementation

---

Trading/Exchange/ftx/ftx_exchange.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/600

[FTX] Add basic subaccount support

---

.github/workflows/main.yml
Trading/Exchange/binance/tests/test_sandbox.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/560
Requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/547

[Binance] Add real tests in sandbox

---

Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py
Services/Interfaces/web_interface/models/backtesting.py
Services/Interfaces/web_interface/static/js/common/data_collector_util.js

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/141

[WebInterface][DataCollector] fix variables names

---

Services/Interfaces/telegram_bot_interface/telegram_bot.py

Require : https://github.com/Drakkar-Software/OctoBot-Services/pull/109

[TelegramBotInterface] Add restart command

---

Trading/Exchange/ftx_websocket_feed/ftx_websocket.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/609

[WS][FTX] Update feeds

---

.github/workflows/main.yml

requires https://github.com/Drakkar-Software/OctoBot/pull/1840

[CI] Migrate to s3 usage

---

Trading/Exchange/okex_websocket_feed/okex_websocket.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/609

[WS][OKEx] Update feeds

---

Services/Interfaces/web_interface/templates/backtesting.html

https://feedback.octobot.online/posts/101/get-historical-data-button-on-the-top

[WebInterface][Backtesting] Displace Data-Collector button

---

Services/Interfaces/web_interface/advanced_templates/advanced_layout.html
Services/Interfaces/web_interface/templates/layout.html

Fix : https://github.com/Drakkar-Software/OctoBot/issues/1870

[WebInterface] Upgrade select2 to 4.1.0

---

Services/Interfaces/web_interface/static/js/components/strategy_design.js
Services/Interfaces/web_interface/templates/strategy_design.html

added screen size toggles and some small improvements

[ScriptedTrading][WebInterface]

---

Services/Interfaces/web_interface/models/trading.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/656

[WebInterface] Migrate to Asset

---

.github/workflows/main.yml
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
Trading/Mode/grid_trading_mode/grid_trading.py
Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

From https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/627

[Mode] Fix tests with Assets

---

Services/Interfaces/web_interface/controllers/community_authentication.py

docs:
https://wtforms.readthedocs.io/en/3.0.x/fields/#wtforms.fields.EmailField

[WebInterface] update wtforms import

---

Services/Interfaces/web_interface/advanced_controllers/tentacles.py
Services/Interfaces/web_interface/login/__init__.py
Services/Interfaces/web_interface/login/web_login_manager.py
Services/Interfaces/web_interface/templates/login.html
Services/Interfaces/web_interface/tests/test_browse_all_pages.py

[WebInterface] require login to manage tentacles

---

Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/config_tentacle.html
Trading/Exchange/hollaex/__init__.py
Trading/Exchange/hollaex/config/hollaex.json
Trading/Exchange/hollaex/config/hollaex_schema.json
Trading/Exchange/hollaex/hollaex_exchange.py
Trading/Exchange/hollaex/metadata.json
Trading/Exchange/hollaex/resources/hollaex.md
Trading/Exchange/hollaex/tests/__init__.py

remaining: orders tests
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/674/files

[Exchanges] init hollaex

---

Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/static/js/components/profile_management.js
Services/Interfaces/web_interface/templates/components/config/profile_tab.html
Services/Interfaces/web_interface/templates/profile.html

[WebInterface] allow profile import from url

---

Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

contains https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/662
from [agoria555](https://github.com/agoria555)

case not sensitive anymore with buy and sell order from tradingview

---

Trading/Exchange/bitget/__init__.py
Trading/Exchange/bitget/bitget_exchange.py
Trading/Exchange/bitget/metadata.json
Trading/Exchange/bitget/resources/bitget.md
Trading/Exchange/bitget/tests/__init__.py
Trading/Exchange/bitget_websocket_feed/__init__.py
Trading/Exchange/bitget_websocket_feed/bitget_websocket.py
Trading/Exchange/bitget_websocket_feed/metadata.json
Trading/Exchange/bitget_websocket_feed/tests/__init__.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/715

[Exchanges] add Bitget

---

Trading/Exchange/bybit/bybit_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/714

[Exchanges] rename get_pair_market_type

---

Services/Interfaces/web_interface/controllers/community_authentication.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1996

[WebInterface] update for async authenticator.login

---

Services/Interfaces/telegram_bot_interface/telegram_bot.py
Services/Interfaces/web_interface/models/configuration.py
Services/Services_bases/reddit_service/reddit.py

fixes:
- reddit service start on binary
- telegram bot message edit handling
- web interface coingecko ratelimit details error

Fix interfaces

---

Services/Interfaces/web_interface/api/devices.py
Services/Interfaces/web_interface/static/js/components/community.js
Services/Interfaces/web_interface/templates/community_login.html

requires https://github.com/Drakkar-Software/OctoBot/pull/2017

[WebInterface] update for new backend

---

Services/Interfaces/web_interface/flask_util/file_services.py
Services/Interfaces/web_interface/templates/community_login.html

also adds this "beta" tag when beta is enabled:

[WebInterface] fix send_file

---

Services/Interfaces/web_interface/__init__.py
Services/Interfaces/web_interface/advanced_controllers/tentacles.py
Services/Interfaces/web_interface/flask_util/__init__.py
Services/Interfaces/web_interface/flask_util/json_provider.py
Services/Interfaces/web_interface/flask_util/template_filters.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/tentacles.py
Services/Interfaces/web_interface/static/js/components/tentacles_configuration.js
Services/Interfaces/web_interface/templates/about.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/web.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2026

add Beta dl

---

Services/Interfaces/web_interface/controllers/backtesting.py
Services/Interfaces/web_interface/models/backtesting.py

replaces https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/687 (allow custom exchange type part)
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/133

[Backtesting] allow custom exchange type

---

Evaluator/TA/volatility_evaluator/config/StochasticRSIVolatilityEvaluator_schema.json
Evaluator/TA/volatility_evaluator/volatility.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/models/profiles.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/731

Errors management

---

Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/templates/about.html
Trading/Exchange/ascendex/ascendex_exchange.py
Trading/Exchange/bithumb/bithumb_exchange.py
Trading/Exchange/bittrex/bittrex_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/ftx/ftx_exchange.py
Trading/Exchange/kraken/kraken_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/wavesexchange/wavesexchange_exchange.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py
Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
Trading/Mode/remote_trading_signals_trading_mode/tests/__init__.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/733
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/143
requires https://github.com/Drakkar-Software/OctoBot/pull/2037

fix exchanges and trading signal issues

---

Services/Interfaces/web_interface/api/trading.py
Services/Interfaces/web_interface/static/js/components/trading.js
Services/Interfaces/web_interface/templates/macros/tables.html
Services/Interfaces/web_interface/templates/trading.html
Trading/Mode/daily_trading_mode/daily_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/135

[WebInterface] add close position button

---

Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
Trading/Mode/remote_trading_signals_trading_mode/resources/RemoteTradingSignalsTradingMode.md
Trading/Mode/remote_trading_signals_trading_mode/tests/__init__.py
Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/751

[RemoteTradingSignals] handle minimum order amount rounding

---

Evaluator/Strategies/mixed_strategies_evaluator/config/TechnicalAnalysisStrategyEvaluator.json
Evaluator/Strategies/mixed_strategies_evaluator/mixed_strategies.py
Evaluator/Strategies/mixed_strategies_evaluator/resources/TechnicalAnalysisStrategyEvaluator.md

requires https://github.com/Drakkar-Software/OctoBot/pull/2074

[TechnicalAnalysisStrategyEvaluator] fix required time frame

---

Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py

reqjuires https://github.com/Drakkar-Software/OctoBot-Trading/pull/760

[RemoteTradingSignalsTradingMode] add tests

---

Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/profile.html

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/760

[WebInterface] check account on sandbox trigger and fix default ex type

---

Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/static/js/components/data_collector.js
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/data_collector.html

data selectors should now always be displayed properly and the 1st enabled exchange is selected by default (previously 1st in config even if not enabled)

[DataCollector] fix data collector selectors and defaut exchange

---

Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/templates/components/config/editable_config.html
Services/Interfaces/web_interface/templates/components/config/trader_card.html

[WebInterface] allow simulated portfolio edit

---

Services/Interfaces/web_interface/advanced_controllers/tentacles.py
Services/Interfaces/web_interface/controllers/home.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/dashboard.py
Services/Interfaces/web_interface/templates/index.html

requires https://github.com/Drakkar-Software/OctoBot/pull/2105

display limits

---

Services/Interfaces/web_interface/api/bots.py
Services/Interfaces/web_interface/controllers/community.py
Services/Interfaces/web_interface/controllers/community_authentication.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/community.py
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/components/community/tentacles_packages.html

Bot select

---

Services/Interfaces/web_interface/controllers/trading.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/community.py
Services/Interfaces/web_interface/templates/trading.html
Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/770
requires https://github.com/Drakkar-Software/OctoBot/pull/2111

[WebInterface] display followed strategy

---

Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/components/config/service_card.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/profile.html

requires https://github.com/Drakkar-Software/OctoBot/pull/2124

Meeting fixes

---

Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/templates/about.html

requires https://github.com/Drakkar-Software/OctoBot/pull/2129

[WebInterface] set profiile origin url on download

---

Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/templates/macros/tentacles.html
Services/Interfaces/web_interface/templates/profile.html

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/305

Web interface update

---

Services/Interfaces/web_interface/models/community.py
Services/Interfaces/web_interface/templates/community_metrics.html
Services/Interfaces/web_interface/templates/macros/tables.html

requires https://github.com/Drakkar-Software/OctoBot/pull/2135

[WebInterface] update metrics display

---

Evaluator/TA/momentum_evaluator/momentum.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/components/community.js
Services/Interfaces/web_interface/static/js/components/navbar.js
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/components/community/bot_selector.html
Services/Interfaces/web_interface/templates/components/community/tentacles_packages.html

https://trello.com/c/2gBKpRuh/42-fix-bugs-vus-le-12-12

[WebInterface] bug fixes

---

Services/Interfaces/web_interface/__init__.py
Services/Interfaces/web_interface/api/__init__.py
Services/Interfaces/web_interface/api/metadata.py
Services/Interfaces/web_interface/flask_util/__init__.py
Services/Interfaces/web_interface/flask_util/cors.py
Services/Interfaces/web_interface/web.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2170

[WebInterface] full CORS handling

---

Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/controllers/profiles.py
Services/Interfaces/web_interface/templates/components/config/profiles.html
Services/Interfaces/web_interface/templates/macros/starting_waiter.html
Services/Interfaces/web_interface/templates/profiles_selector.html

now reboot after page render to make sure waiter is displayed before reboot

[WebInterface] fix profile select reboot

---

Backtesting/collectors/exchanges/exchange_bot_snapshot_data_collector/bot_snapshot_with_history_collector.py
Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py

fixes: ignore missing timeframes (instead of crashing)
new:

[Collector] ignore missing time frames

---

Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/templates/macros/tentacles.html
Services/Interfaces/web_interface/templates/profile.html

display profile name on top 
exchange and trader cards one per row

[WebInterface] improve mobile display

---

Trading/Exchange/bybit_websocket_feed/bybit_websocket.py

(now included in ccxt base parser)

[Bybit] simplify adapter

---

Services/Interfaces/web_interface/controllers/community_authentication.py
Services/Interfaces/web_interface/static/js/components/community.js
Services/Interfaces/web_interface/templates/community_login.html
Services/Interfaces/web_interface/templates/community_register.html
Services/Interfaces/web_interface/templates/components/community/login.html
Services/Interfaces/web_interface/templates/profiles_selector.html

requires https://github.com/Drakkar-Software/OctoBot/pull/2187

[WebInterface] add community register

---

Services/Interfaces/web_interface/flask_util/browsing_data_provider.py

require https://github.com/Drakkar-Software/OctoBot/pull/2194

[WebInterface] reset sessions when no loggedin user in cloud

---

Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py
Trading/Exchange/bitget/bitget_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/kucoin_websocket_feed/kucoin_websocket.py
Trading/Mode/arbitrage_trading_mode/tests/test_arbitrage_trading_mode_producer.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/811

[Exchanges] kucoin futures

---

Services/Interfaces/web_interface/static/js/common/on_load.js
Services/Interfaces/web_interface/static/js/common/required.js
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/profile.html

[WebInterface] import startup messages display

---

Trading/Mode/grid_trading_mode/grid_trading.py
Trading/Mode/grid_trading_mode/resources/GridTradingMode.md
Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py

[GridTrading] add default configuration

---

Meta/Keywords/scripting_library/UI/plots/displayed_elements.py
Meta/Keywords/scripting_library/backtesting/run_data_analysis.py
Services/Interfaces/web_interface/api/trading.py
Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/controllers/home.py
Services/Interfaces/web_interface/controllers/profiles.py
Services/Interfaces/web_interface/controllers/trading.py
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/js/common/cst.js
Services/Interfaces/web_interface/static/js/common/custom_elements.js
Services/Interfaces/web_interface/static/js/common/portfolio_history.js
Services/Interfaces/web_interface/static/js/components/dashboard.js
Services/Interfaces/web_interface/static/js/components/portfolio.js
Services/Interfaces/web_interface/static/js/components/trades.js
Services/Interfaces/web_interface/templates/components/config/trader_card.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/templates/profile.html
Services/Interfaces/web_interface/templates/trades.html
Services/Interfaces/web_interface/tests/__init__.py
Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_producer.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/825

Load history

---

Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/templates/community_login.html
Services/Interfaces/web_interface/templates/components/community/login.html
Services/Interfaces/web_interface/templates/login.html

requires https://github.com/Drakkar-Software/OctoBot-tentacles

[WebInterface] add recover password url

---

Services/Interfaces/web_interface/templates/index.html

[WebInterface] add profitability reset tooltip

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/js/common/custom_elements.js

requires https://github.com/Drakkar-Software/OctoBot/pull/2231

[WebInterface] improve historical portfolio display and fix reset

---

Services/Interfaces/web_interface/static/js/components/dashboard.js
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/portfolio.html
Services/Interfaces/web_interface/websockets/dashboard.py

[WebInterface] improve history display

---

Meta/Keywords/scripting_library/orders/cancelling.py
Meta/Keywords/scripting_library/orders/order_tags.py
Services/Interfaces/web_interface/controllers/commands.py
Services/Interfaces/web_interface/models/profiles.py

here are my answers to your open qustions:
- [Services] fix commands response before shutdown
we should use a shorter delay
I changed it to 0.1 which I also tested multiple times

Multiple minor fixes

---

Services/Interfaces/web_interface/static/js/common/tutorial.js
Services/Interfaces/web_interface/static/js/components/automations.js
Services/Interfaces/web_interface/static/js/components/config_tentacle.js
Services/Interfaces/web_interface/templates/automations.html

[WebInterface] add/remove automations button

---

Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py
Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/846

[TradingMode] handle cancel_order errors

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/pnl_history.js
Services/Interfaces/web_interface/templates/trading.html

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/863

improve pnl display

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bitget/bitget_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/cryptocom/cryptocom_exchange.py
Trading/Exchange/cryptocom_websocket_feed/__init__.py
Trading/Exchange/cryptocom_websocket_feed/cryptocom_websocket.py
Trading/Exchange/cryptocom_websocket_feed/metadata.json
Trading/Exchange/hollaex/hollaex_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/864

[Exchanges] ensure fees on closed orders

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/templates/layout.html

avoid rows with 0 value PNL in details tab

[WebInterface] hide 0 value PNL

---

Meta/Keywords/scripting_library/tests/__init__.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/868

[Tests] update for ValueConverter

---

Meta/Keywords/scripting_library/UI/plots/displayed_elements.py
Services/Interfaces/web_interface/models/backtesting.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/340

[Display] handle missing run metadata for live displayed elements

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/js/components/trading.js
Services/Interfaces/web_interface/templates/trading.html

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/873

[WebInterface] add ref market value in trades

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/js/common/pnl_history.js
Services/Interfaces/web_interface/templates/trading.html
Services/Services_bases/telegram_service/telegram.py

(added the + XYZ when fees are paid in a extra currency)
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/872

[WebInterface] improve fees in pnl history

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/js/common/pnl_history.js

[WebInterface] add pnl filter and tooltip by exchange, symbol and trades

---

Services/Interfaces/web_interface/models/profiles.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/components/profile_management.js
Services/Interfaces/web_interface/templates/components/config/profiles.html
profiles/arbitrage_trading/profile.json
profiles/copy_trading/profile.json
profiles/daily_trading/profile.json
profiles/dip_analyser/profile.json
profiles/grid_trading/profile.json
profiles/non-trading/profile.json
profiles/signal_trading/profile.json
profiles/simple_dca/profile.json
profiles/staggered_orders_trading/profile.json
profiles/tradingview_trading/profile.json

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/346
requires https://github.com/Drakkar-Software/OctoBot/pull/2297

Profiles risk & complexity

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bitget/bitget_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/coinbase/__init__.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/coinbase/metadata.json
Trading/Exchange/coinex/coinex_exchange.py
Trading/Exchange/configurable_default_ccxt_rest/configurable_default_rest_ccxt_exchange.py
Trading/Exchange/huobi/huobi_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/okx/okx_exchange.py
Trading/Exchange/phemex/phemex_exchange.py

requries trading version with https://github.com/Drakkar-Software/OctoBot-Trading/pull/880

add Coinbase

---

Evaluator/TA/ai_evaluator/__init__.py
Evaluator/TA/ai_evaluator/ai.py
Evaluator/TA/ai_evaluator/config/GPTEvaluator.json
Evaluator/TA/ai_evaluator/metadata.json
Evaluator/TA/ai_evaluator/resources/GPTEvaluator.md
Evaluator/TA/ai_evaluator/tests/test_ai.py
Services/Services_bases/gpt_service/__init__.py
Services/Services_bases/gpt_service/gpt.py
Services/Services_bases/gpt_service/metadata.json

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/152
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/202

init gpt evaluator

---

Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py
Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/884

[Orders] add update_type to channel

---

Evaluator/TA/ai_evaluator/ai.py
Evaluator/TA/ai_evaluator/resources/GPTEvaluator.md

require https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/203

[GPT] improve backtesting and timeframe error handling

---

Trading/Exchange/hollaex/hollaex_exchange.py

allows to work with hollaex exchange that are not supporting ws

[Hollaex] allow disable websockets for custom exchanges

---

Backtesting/collectors/exchanges/exchange_bot_snapshot_data_collector/bot_snapshot_with_history_collector.py

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/174

[Collector] auto fix datafile integrity issues

---

Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/trading_view_signals_trading_mode/resources/TradingViewSignalsTradingMode.md
Trading/Mode/trading_view_signals_trading_mode/tests/test_trading_view_signals_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

handle take profit  and stop loss on position increasing orders. used by trading view trading mode

Take profit

---

Services/Interfaces/web_interface/static/js/components/config_tentacle.js
Services/Interfaces/web_interface/templates/config_tentacle.html

[WebInterface] add date selector on tentacles config

---

Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py
Services/Interfaces/web_interface/models/backtesting.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/phemex/phemex_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/898

[Exchanges] update for ccxt 3.0.74

---

Evaluator/TA/ai_evaluator/ai.py
Services/Services_bases/gpt_service/gpt.py

requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/204

[GPTEvaluator] allow GPT model selector

---

Meta/Keywords/scripting_library/backtesting/default_backtesting_run_analysis_script.py
Meta/Keywords/scripting_library/backtesting/run_data_analysis.py
Meta/Keywords/scripting_library/tests/backtesting/test_run_data.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/359
requires https://github.com/Drakkar-Software/OctoBot/pull/2321

Market profit

---

Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/arbitrage_trading_mode/tests/test_arbitrage_trading_mode_producer.py

[ArbitrageTrading] add disable long/short setting

---

Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/917

[Signals] do not create duplicate orders

---

Services/Interfaces/web_interface/static/js/common/candlesticks.js
Services/Interfaces/web_interface/web.py

[WebInterface] improve orders display

---

Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/trading.html
Services/Interfaces/web_interface/websockets/dashboard.py

[WebInterface] improve home display

---

Trading/Mode/daily_trading_mode/daily_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/370

[TradingModes] use UserInputOtherSchemaValuesTypes.DEPENDENCIES

---

Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/controllers/home.py
Services/Interfaces/web_interface/controllers/reboot.py
Services/Interfaces/web_interface/controllers/trading.py
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/static/js/common/util.js
Services/Interfaces/web_interface/static/js/components/configuration.js
Services/Interfaces/web_interface/static/js/components/portfolio.js
Services/Interfaces/web_interface/static/js/components/trading.js
Services/Interfaces/web_interface/templates/accounts.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/macros/cards.html
Services/Interfaces/web_interface/templates/profile.html
Services/Interfaces/web_interface/templates/symbol_market_status.html
Services/Interfaces/web_interface/templates/trading.html
Services/Interfaces/web_interface/templates/trading_type_selector.html
Services/Interfaces/web_interface/templates/wait_reboot.html

UI improvements

---

Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
Trading/Mode/trading_view_signals_trading_mode/tests/test_trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/923

[Modes] update tests for fix % based amount

---

Trading/Exchange/kucoin_websocket_feed/kucoin_websocket.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/938

[Kucoin][Websocket] use RECREATE_CLIENT_ON_DISCONNECT

---

Services/Interfaces/web_interface/templates/config_tentacle.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/macros/cards.html

Web improvements

---

Services/Interfaces/web_interface/__init__.py
Services/Interfaces/web_interface/controllers/logs.py
Services/Interfaces/web_interface/static/js/components/logs.js
Services/Interfaces/web_interface/templates/logs.html
Services/Interfaces/web_interface/templates/macros/tables.html

[WebInterface] add notifications history

---

Services/Interfaces/web_interface/controllers/trading.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/static/js/common/candlesticks.js
Trading/Exchange/bingx/__init__.py
Trading/Exchange/bingx/bingx_exchange.py
Trading/Exchange/bingx/metadata.json
Trading/Exchange/bingx/resources/bingx.md
Trading/Exchange/coinbase/coinbase_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2381

[Coinbase] ccxt update

---

Services/Services_bases/telegram_service/telegram.py

disables new logger (from https://github.com/Drakkar-Software/OctoBot-Services/pull/160 update)

[telegram] disable updated loggers

---

Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/okx/okx_exchange.py
Trading/Mode/grid_trading_mode/grid_trading.py
Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/956

[Kucoin][OKX] add get_account_id

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/coinbase_pro/coinbase_pro_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2392

[Exchanges] move order id parse in trade in default parser

---

Services/Interfaces/web_interface/controllers/home.py
Services/Interfaces/web_interface/models/__init__.py
Services/Interfaces/web_interface/models/configuration.py
Services/Interfaces/web_interface/templates/index.html
Services/Services_bases/telegram_service/telegram.py

[WebInterface] sandbox badge

---

Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/972

[TradingModes] update get_split_orders_count_and_increment call

---

Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/986

[RemoteTradingSignalsModeConsumer] improve min funds handling

---

Evaluator/Strategies/dip_analyser_strategy_evaluator/tests/test_dip_analyser_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator/tests/test_move_signals_strategy_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/990
reqiuires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1082

[Strategies] update tests for non instant fill orders

---

Trading/Mode/dca_trading_mode/dca_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/991

[DCA] add use_init_entry_orders param

---

Meta/Keywords/scripting_library/tests/__init__.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1000

Context fix

---

Trading/Exchange/bingx/bingx_exchange.py
Trading/Exchange/bingx/tests/__init__.py
Trading/Exchange/bingx_websocket_feed/__init__.py
Trading/Exchange/bingx_websocket_feed/bingx_websocket.py
Trading/Exchange/bingx_websocket_feed/metadata.json

requires https://github.com/Drakkar-Software/OctoBot/pull/2477

[Bingx] update after tests

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/okx/okx_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1010

[Exchanges] use factorized contract size handling for orders

---

Evaluator/TA/ai_evaluator/ai.py
Evaluator/TA/ai_evaluator/config/GPTEvaluator.json
Evaluator/TA/ai_evaluator/resources/GPTEvaluator.md
Services/Services_bases/gpt_service/gpt.py
profiles/gpt_trading/specific_config/GPTEvaluator.json

[ChatGPT] improve evaluator config

---

Services/Interfaces/web_interface/static/js/common/backtesting_util.js

Show profitability on backtesting even if error

---

Services/Interfaces/web_interface/static/js/components/backtesting.js
Services/Interfaces/web_interface/static/js/components/data_collector.js
Services/Interfaces/web_interface/templates/backtesting.html
Services/Interfaces/web_interface/templates/data_collector.html

[WebInterface] improve backtesting data select display

---

Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Trading/Exchange/bingx/bingx_exchange.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/trading_view_signals_trading_mode/resources/TradingViewSignalsTradingMode.md
Trading/Mode/trading_view_signals_trading_mode/tests/test_trading_view_signals_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1024
requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1168

[DCATradingMode] fix create order

---

Evaluator/Strategies/dip_analyser_strategy_evaluator/tests/test_dip_analyser_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
Evaluator/Strategies/move_signals_strategy_evaluator/tests/test_move_signals_strategy_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1027

[Tests] update values for order fill price fixes

---

Trading/Mode/trading_view_signals_trading_mode/tests/test_trading_view_signals_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1034

[TradingView] don't implicitely adapt order input to holdings

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/cryptocom/cryptocom_exchange.py
Trading/Exchange/htx/htx_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/mexc/mexc_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1035

Ccxt update

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/okx/okx_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1037

[Exchanges] update for ccxt 4.2.77

---

Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py

remaining: tests
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1041

[TradingMode] add last_activity

---

Services/Interfaces/web_interface/templates/about.html

[WebInterface] add deployment link

---

Services/Interfaces/web_interface/models/configuration.py

requires https://github.com/Drakkar-Software/OctoBot

[WebInterface] use ssl_fallback_aiohttp_client_session

---

.github/workflows/main.yml
Meta/Keywords/scripting_library/tests/orders/position_size/test_amount.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1055

[DCATrading] cancel orders before creating new ones

---

Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2624

[IndexTrading] ignore disabled currencies

---

Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1063

[IndexTrading] use limit orders when markets orders are not available

---

Trading/Exchange/bitfinex/bitfinex_exchange.py
Trading/Exchange/bitstamp/bitstamp_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/hitbtc/hitbtc_exchange.py
Trading/Exchange/hollaex/hollaex_exchange.py
Trading/Exchange/htx/htx_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/ndax/ndax_exchange.py
Trading/Exchange/phemex/phemex_exchange.py
Trading/Exchange/wavesexchange/wavesexchange_exchange.py

(call used in mocks, therefore requires the same type of args)

[Exchanges] use the same ohlcv call

---

Services/Services_bases/webhook_service/webhook.py
Services/Services_feeds/trading_view_service_feed/trading_view_feed.py
Trading/Mode/index_trading_mode/index_trading.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2637

[Webhook] support community feed based trigger

---

Services/Interfaces/web_interface/templates/extensions.html

[WebInterface] add contact email on /extension

---

Services/Interfaces/web_interface/advanced_templates/advanced_layout.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/logs.html

improves datatable display, especially on trades tables

[WebInterface] update datatables version

---

Services/Interfaces/web_interface/controllers/configuration.py
Services/Interfaces/web_interface/static/js/components/automations.js
Services/Interfaces/web_interface/static/js/components/config_tentacle.js
Services/Interfaces/web_interface/templates/config_tentacle.html

based on user feedback who was looking for a way to restart his bot when configuring his trading mode

[WebInterface] add save and restart on tentacles config

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/coinex/coinex_exchange.py
Trading/Exchange/cryptocom/cryptocom_exchange.py
Trading/Exchange/hollaex/hollaex_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/okx/okx_exchange.py
Trading/Mode/index_trading_mode/index_trading.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2671

[Exchanges] add fetch cancelled orders utils

---

Services/Interfaces/web_interface/models/dashboard.py
Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/candlesticks.js
Services/Interfaces/web_interface/static/js/components/dashboard.js
Services/Interfaces/web_interface/templates/index.html

improved visibility & trades tooltip & fix display glitch
after
before

[WebInterface] improve candlesticks UI

---

Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/candlesticks.js
Services/Interfaces/web_interface/templates/components/config/currency_card.html
Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Services/Interfaces/web_interface/templates/components/config/service_card.html
Services/Interfaces/web_interface/templates/trading_type_selector.html

[WebInterface] improve dark UI

---

Services/Interfaces/web_interface/models/trading.py
Services/Interfaces/web_interface/templates/trading.html
Trading/Exchange/kucoin_websocket_feed/kucoin_websocket.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1074

Kucoin: fix max 100 feeds websocket issue

---

Trading/Mode/grid_trading_mode/grid_trading.py
Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/resources/IndexTradingMode.md

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1075

[IndexTrading] support custom distribution config

---

Services/Interfaces/web_interface/templates/components/config/exchange_card.html
Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bitget/bitget_exchange.py
Trading/Exchange/bitmart/bitmart_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/coinex/coinex_exchange.py
Trading/Exchange/htx/htx_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2708

[WebInterface] add UID creds

---

Services/Interfaces/web_interface/templates/components/config/exchange_card.html

[WebInterface] make exchange password field shorter

---

Trading/Exchange/hollaex_autofilled/hollaex_autofilled_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2710

[Hollaex] make autofilled exchange more flexible

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/okx/okx_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1092

[OKX] update leverage parser

---

Trading/Exchange/bingx/bingx_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/mexc/mexc_exchange.py
Trading/Exchange/okx/okx_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2739

[Exchanges] add EXCHANGE_AUTHENTICATION_ERRORS

---

Services/Interfaces/web_interface/static/css/style.css
Services/Interfaces/web_interface/static/js/common/resources_rendering.js
Trading/Mode/trading_view_signals_trading_mode/resources/TradingViewSignalsTradingMode.md

[TradingView] add generator link in description

---

Trading/Mode/dca_trading_mode/resources/DCATradingMode.md
Trading/Mode/trading_view_signals_trading_mode/resources/TradingViewSignalsTradingMode.md

[TradingView] add custom automations video

---

Services/Interfaces/web_interface/models/configuration.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/448
requires https://github.com/Drakkar-Software/OctoBot/pull/2805

[WebInterface] avoid html in logs

---

Trading/Exchange/hollaex_autofilled/hollaex_autofilled_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2839

[Exchanges] make get_rest_name a classmethod

---

Services/Services_bases/gpt_service/gpt.py

related to https://github.com/Drakkar-Software/OctoBot/issues/2841

[GPT] make incompatible model errors more clear

---

Meta/Keywords/scripting_library/tests/orders/order_types/test_multiple_orders_creation.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/trading_view_signals_trading_mode/tests/test_trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2865

[Modes] add trading_mode.ensure_supported

---

Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py

requries https://github.com/Drakkar-Software/OctoBot-Trading/pull/1175

[Dca][DailyTrading] adapt order fees for last order only

---

Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1180 in octobot
(fixes a rare staggered/grid init IndexError)

[TradingModes] fix staggered init

---

Services/Interfaces/web_interface/advanced_templates/advanced_strategy_optimizer.html
Services/Interfaces/web_interface/controllers/community_authentication.py
Services/Interfaces/web_interface/flask_util/context_processor.py
Services/Interfaces/web_interface/templates/about.html
Services/Interfaces/web_interface/templates/community.html
Services/Interfaces/web_interface/templates/components/community/cloud_strategies.html
Services/Interfaces/web_interface/templates/components/community/octobot_cloud_description.html
Services/Interfaces/web_interface/templates/components/community/octobot_cloud_features.html
Services/Interfaces/web_interface/templates/extensions.html
Services/Interfaces/web_interface/templates/footer.html
Services/Interfaces/web_interface/templates/index.html
Services/Interfaces/web_interface/templates/welcome.html
Services/Services_bases/gpt_service/gpt.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2903

[Web] replace landing url by community url

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bitget/bitget_exchange.py
Trading/Exchange/bitmart/bitmart_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/coinex/coinex_exchange.py
Trading/Exchange/htx/htx_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/mexc/mexc_exchange.py
Trading/Exchange/phemex/phemex_exchange.py
Trading/Mode/index_trading_mode/index_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1193
requires https://github.com/Drakkar-Software/OctoBot/pull/2912

[IndexTrading] log intermediary ref market holdings & update buy market

---

Services/Interfaces/web_interface/models/trading.py

fix: concat numbers instead of str when multiple exchanges history is available

[WebInterface] fix multi exchange historical pf display

---

Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
Trading/Mode/remote_trading_signals_trading_mode/tests/__init__.py
Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py
Trading/Mode/trading_view_signals_trading_mode/tests/test_trading_view_signals_trading.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1195
requires https://github.com/Drakkar-Software/OctoBot/pull/2919

[TradingView] handle TRAILING_PROFILE for balanced order groups

---

Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

fixes https://github.com/Drakkar-Software/OctoBot/issues/2711

[Staggered] fix PNL on sell+buy issue

---

Trading/Mode/index_trading_mode/index_trading.py

prevent error log when ref market is removed from distribution (when going full crypto exposure)

[IndexTrading] handle ref market change distrib

---

Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1205

[DCA] fix skipped entry orders when cancelling prev ones is available

---

Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py

require https://github.com/Drakkar-Software/OctoBot/pull/2959

[SignalTradingMode] handle POSITION_PERCENT_ALIAS

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bingx/bingx_exchange.py
Trading/Exchange/bybit/bybit_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/okx/okx_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1228

fix edit orders

---

Trading/Exchange/kucoin/kucoin_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1232

[Kucoin] fix set_leverage for cross positions

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bingx/bingx_exchange.py
Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Exchange/hollaex/hollaex_exchange.py
Trading/Exchange/hollaex_websocket_feed/hollaex_websocket.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/mexc/mexc_exchange.py
Trading/Exchange/okx/okx_exchange.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1233

[Exchanges] add get_max_orders_count

---

Trading/Exchange/hollaex/hollaex_exchange.py
Trading/Exchange/hollaex_autofilled/hollaex_autofilled_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1524
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1234

HollaEx backtesting

---

Trading/Exchange/hollaex/hollaex_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1235

[HollaEx] use fetched fees

---

Trading/Exchange/coinbase/coinbase_exchange.py
Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1252

Index sync policy

---

Evaluator/TA/trend_evaluator/resources/SuperTrendEvaluator.md
Evaluator/TA/trend_evaluator/trend.py

Thanks to DemFi for identifying the issue

[SuperTrend] fix and improve supertrend evaluator

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/kucoin/kucoin_exchange.py
Trading/Exchange/mexc/mexc_exchange.py

uses https://github.com/Drakkar-Software/OctoBot-Trading/pull/1258

[Exchanges] add local fees

---

Services/Services_bases/gpt_service/gpt.py

requires https://github.com/Drakkar-Software/OctoBot/pull/3040

[GPTService] update for openai bump

---

Trading/Exchange/binance/binance_exchange.py
Trading/Exchange/bitmart/bitmart_exchange.py
Trading/Exchange/hollaex/hollaex_exchange.py

requires https://github.com/Drakkar-Software/OctoBot/pull/3043

[Exchanges] update for ccxt bump

---

Services/Interfaces/web_interface/advanced_templates/advanced_layout.html
Services/Interfaces/web_interface/api/metadata.py
Services/Interfaces/web_interface/templates/components/community/user_details.html
Services/Interfaces/web_interface/templates/components/config/profiles.html
Services/Interfaces/web_interface/templates/layout.html
Services/Interfaces/web_interface/templates/profile.html

fixes https://github.com/Drakkar-Software/OctoBot/issues/2918

[WebInterface] cache latest version fetch

---

Trading/Mode/arbitrage_trading_mode/arbitrage_trading.py
Trading/Mode/daily_trading_mode/daily_trading.py
Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_producer.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
Trading/Mode/grid_trading_mode/grid_trading.py
Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
Trading/Mode/index_trading_mode/index_trading.py
Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py
Trading/Mode/market_making_trading_mode/market_making_trading.py
Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
Trading/Mode/remote_trading_signals_trading_mode/tests/__init__.py
Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py
Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py

requires https://github.com/Drakkar-Software/OctoBot/pull/3046

Signals dependencies

---

Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Trading/Mode/dca_trading_mode/dca_trading.py
Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py

requires https://github.com/Drakkar-Software/OctoBot/pull/3047

partially filled orders

---

Services/Services_bases/gpt_service/gpt.py

fixes https://github.com/Drakkar-Software/OctoBot/issues/3060

[GPT] fix deprecated max_completion_tokens param and handle GPT-5

---

Trading/Exchange/kucoin/kucoin_exchange.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1281

[Kucoin] enable tickers and market fees autofixer
