Drakkar-Software/OctoBot-Tentacles

- Evaluator/RealTime/instant_fluctuations_evaluator.py
- Evaluator/Strategies/SimpleMarketMakingStrategiesEvaluator.json
- Evaluator/Strategies/market_making_startegy_evaluator.py
- Trading/Mode/MarketMakerTradingMode.json
- Trading/Mode/daily_trading_mode.py
- Trading/Mode/market_maker_trading_mode.py
- tests/Trading/Mode/test_market_marker_trading_mode.py
> [Trading Mode] Implement market making

- Backtesting/collectors/exchanges/exchange_history_collector.py
- Interfaces/web/models/backtesting.py
- Interfaces/web/models/dashboard.py
(after https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/16 and https://github.com/Drakkar-Software/OctoBot-Trading/pull/87)
> display backtesting charts when bot is started with backtesting argument

- Interfaces/web/web_interface.py
- Services/service_feeds/reddit_service_feed.py
- Services/service_feeds/twitter_service_feed.py
without websockets:
additionnally, flask is creating a thread for each request (then this thread is left unused) => to fix it we need to run the server on a real server :)
> name web interface and service feed threads 

- Services/Interfaces/web_interface/templates/backtesting.html
- Services/Interfaces/web_interface/templates/config_tentacle.html
- Trading/Mode/arbitrage_trading_mode/arbitrage_trading_mode.py
need to adapt backtesting to octobot channels, require multiple exchange and update trading mode config to trade with selected exchanges.
Summarized in https://github.com/Drakkar-Software/OctoBot-Tentacles/issues/259
> make arbitrage trading mode not backtestable

- Trading/Mode/staggered_orders_trading_mode/config/StaggeredOrdersTradingMode_schema.json
- Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
- Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py
- azure-pipelines.yml
https://github.com/Drakkar-Software/OctoBot-Tentacles/issues/294
* Use existing orders as initial orders (do not create new orders during initialization)
* Add a delay between order fill and mirror order placement to profit from fast bump/dump increased spread
requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/301
> Update staggered orders

- Trading/Exchange/coinbase_pro/coinbase_pro_exchange.py
Should resolve https://github.com/Drakkar-Software/OctoBot/issues/1531. Was raising "ccxt.base.errors.ExchangeError: coinbasepro Invalid parameter range - limit" when calling `_open_orders_fetch_and_push` in OctoBot-Trading `OrderUpdater` task.
> [Trading][CoinbasePro] Fix fetch_open_order max pagination

- Services/Interfaces/web_interface/static/js/common/json_editor_settings.js
in tentacles config, when the current config is missing config keys, display them anyway
> [WebInterface] display all config options but default

- Trading/Exchange/bitmax/bitmax_exchange.py
Ticker was ignored because Timestamp value was None.
It's now fixed :
> [Trading][Exchanges][Bitmax] Fix fetch_ticker

- Evaluator/Strategies/mixed_strategies_evaluator/tests/test_simple_strategy_evaluator.py
- Evaluator/Strategies/mixed_strategies_evaluator/tests/test_technical_analysis_strategy_evaluator.py
- Evaluator/Strategies/move_signals_strategy_evaluator/tests/test_move_signals_strategy_evaluator.py
- Trading/Mode/daily_trading_mode/daily_trading.py
- Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
Migrate to decimal order adapter to prevent truncating order quantity when calling `check_and_adapt_order_details_if_necessary`
> [Trading][DailyTradingMode] Fix decimal errors

- Services/Interfaces/web_interface/templates/components/config/editable_config.html
issue was that symbols that are not on selected exchange were cleared from the select options without the user actually changing the config (issue introduced in https://github.com/Drakkar-Software/OctoBot-Tentacles/commit/48f93133a131cd563c0d8dcb8342f9644f23add7à
> web interface editor display

- Trading/Mode/daily_trading_mode/daily_trading.py
- Trading/Mode/dip_analyser_trading_mode/dip_analyser_trading.py
- Trading/Mode/dip_analyser_trading_mode/tests/test_dip_analyser_trading_mode.py
- Trading/Mode/grid_trading_mode/grid_trading.py
- Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
- Trading/Mode/trading_view_signals_trading_mode/resources/TradingViewSignalsTradingMode.md
- Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/771
enabled for all trading modes that were missing it, example with daily trading mode
> [TradingModes] add custom order size

- Services/Interfaces/web_interface/models/configuration.py
fixes 
```
extended.append(MERGED_CCXT_EXCHANGES[exchange])
AttributeError: 'dict' object has no attribute 'append'
```
> [WebInterface] fix _add_merged_exchanges error

- Trading/Exchange/binance/binance_exchange.py
- Trading/Exchange/bitget/bitget_exchange.py
- Trading/Exchange/coinex/coinex_exchange.py
- Trading/Exchange/huobi/huobi_exchange.py
requires PR in trading -> [CCXT] add reduce only to create order (future exchange tentacles must implement it)
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/814
> [CreateOrder] add reduce only parameter (futures tentacles must implement it)

- Services/Interfaces/web_interface/templates/layout.html
md:
lg:
xl:
(fix navbar elements overflowing in md and lg display)
> [WebInterface] improve md screen display

- Services/Interfaces/web_interface/static/js/common/candlesticks.js
-set showlegend to "false" (not really necessary and takes up precious screen space)
-set scrollZoom to "false" (less accidental zooming while scrolling page)
> Tweak graphs on dashboard

- Evaluator/RealTime/instant_fluctuations_evaluator/instant_fluctuations.py
- Evaluator/Social/trends_evaluator/trends.py
- Evaluator/Strategies/dip_analyser_strategy_evaluator/dip_analyser_strategy.py
can't change timeframes in live mode as other timeframes won't be available (require restart)
> [Evaluators] disable hot timeframe change

- Trading/Exchange/binance/binance_exchange.py
- Trading/Exchange/kucoin/kucoin_exchange.py
- Trading/Exchange/okx/okx_exchange.py
- Trading/Mode/dca_trading_mode/dca_trading.py
- Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
- Trading/Mode/grid_trading_mode/grid_trading.py
- Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
- Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
- Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/984
todo:
- ✅ DCA
- grid
> [TradingModes] init optimize_initial_portfolio

- Services/Services_bases/webhook_service/webhook.py
Resolves https://feedback.octobot.online/open-source/p/add-support-for-ngrok-static-domains
> [Webhook] Add custom domain support

- Evaluator/TA/ai_evaluator/ai.py
- Evaluator/TA/ai_evaluator/resources/GPTEvaluator.md
- Evaluator/TA/ai_evaluator/tests/test_ai.py
- Meta/Keywords/scripting_library/UI/plots/displayed_elements.py
- Meta/Keywords/scripting_library/tests/exchanges/__init__.py
- Services/Interfaces/web_interface/controllers/configuration.py
- Services/Services_bases/gpt_service/gpt.py
requires https://github.com/Drakkar-Software/OctoBot/pull/2450
> [GPT] enable historical signals fetch

- Services/Interfaces/web_interface/flask_util/browsing_data_provider.py
necessary for cloud octobot to trade on newer coins when created long ago
> Expiring cache

- Evaluator/Strategies/blank_strategy_evaluator/blank_strategy.py
- Trading/Mode/dca_trading_mode/config/DCATradingMode.json
- Trading/Mode/dca_trading_mode/dca_trading.py
- Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
- Trading/Mode/grid_trading_mode/grid_trading.py
- Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
- profiles/simple_dca/specific_config/DCATradingMode.json
- profiles/smart_dca/specific_config/DCATradingMode.json
requires https://github.com/Drakkar-Software/OctoBot/pull/2476
> [DCA][Staggered] init health check

- Services/Interfaces/telegram_bot_interface/telegram_bot.py
- Services/Interfaces/telegram_bot_interface/tests/test_bot_interface.py
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/165
> [Telegram] fix async commands

- Services/Interfaces/web_interface/models/configuration.py
issue is that for some users, coingecko.com works but not api.coingecko.com.
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/426
> [WebInterface] fix coingecko ssl issue

- Services/Interfaces/web_interface/controllers/home.py
- Services/Interfaces/web_interface/templates/index.html
(auto updater is disabled since release url are not available (can't dl from GH releases directly)) => use direct link instead of logging link in a log
> [WebInterface] improve new version notification

- Meta/Keywords/scripting_library/UI/plots/displayed_elements.py
fixes OctoBot-Script indicator plotting issues
> [DisplayElements] fix symbol filter

- Services/Services_bases/gpt_service/gpt.py
requires [Constant] add CONIG_LLM_CUSTOM_BASE_URL
> [GPT] handle custom url

- Trading/Mode/dca_trading_mode/dca_trading.py
- Trading/Mode/index_trading_mode/index_trading.py
- Trading/Mode/index_trading_mode/tests/test_index_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1130
requires https://github.com/Drakkar-Software/OctoBot/pull/2807
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1131
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/450
> [IndexTrading] support historical config and fix chain rebalance

- Trading/Exchange/kucoin/kucoin_exchange.py
- Trading/Exchange/okx/okx_exchange.py
- Trading/Mode/trading_view_signals_trading_mode/trading_view_signals_trading.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1145
> [Exchanges] handle MAX_FETCHED_OHLCV_COUNT

- Trading/Mode/daily_trading_mode/daily_trading.py
- Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
- Trading/Mode/dca_trading_mode/dca_trading.py
- Trading/Mode/dca_trading_mode/tests/test_dca_trading_mode.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1148
> [Modes] reduce_only chained orders when trading futures

- Trading/Exchange/binance/binance_exchange.py
- Trading/Exchange/bingx/bingx_exchange.py
- Trading/Exchange/coinbase/coinbase_exchange.py
- Trading/Exchange/kucoin/kucoin_exchange.py
- Trading/Mode/remote_trading_signals_trading_mode/remote_trading_signals_trading.py
- Trading/Mode/remote_trading_signals_trading_mode/tests/__init__.py
- Trading/Mode/remote_trading_signals_trading_mode/tests/test_remote_trading_signals_trading_consumer.py
requires https://github.com/Drakkar-Software/OctoBot/pull/2849
> trigger above parsing

- Trading/Exchange/mexc/mexc_exchange.py
replaces https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1416
> [MEXC] implement get_all_tradable_symbols

- Services/Interfaces/web_interface/advanced_templates/advanced_index.html
- Services/Interfaces/web_interface/login/web_login_manager.py
error is displayed here instead of in login box, which wrongly makes users think they should login (but they need to enable forced login instead)
> [WebInterface] make forced login message clearer

- Trading/Mode/grid_trading_mode/config/GridTradingMode.json
- Trading/Mode/grid_trading_mode/grid_trading.py
- Trading/Mode/grid_trading_mode/resources/GridTradingMode.md
- Trading/Mode/grid_trading_mode/tests/test_grid_trading_mode.py
- Trading/Mode/staggered_orders_trading_mode/staggered_orders_trading.py
- Trading/Mode/staggered_orders_trading_mode/tests/test_staggered_orders_trading_mode.py
- profiles/grid_trading/specific_config/GridTradingMode.json
- profiles/trailing_grid_trading/profile.json
- profiles/trailing_grid_trading/specific_config/GridTradingMode.json
- profiles/trailing_grid_trading/tentacles_config.json
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1170
> [Grid] add trailing option

- Trading/Mode/daily_trading_mode/daily_trading.py
- Trading/Mode/daily_trading_mode/tests/test_daily_trading_mode_consumer.py
now always consider the max coin ratio param
> [DailyTrading] fix max ratio

- Services/Interfaces/web_interface/models/trading.py
- Trading/Exchange/ascendex/ascendex_exchange.py
- Trading/Exchange/bingx/bingx_exchange.py
- Trading/Exchange/bitfinex/bitfinex_exchange.py
- Trading/Exchange/bitmart/bitmart_exchange.py
- Trading/Exchange/coinbase/coinbase_exchange.py
- Trading/Exchange/hyperliquid/__init__.py
- Trading/Exchange/hyperliquid/hyperliquid_exchange.py
- Trading/Exchange/hyperliquid/metadata.json
- Trading/Exchange/hyperliquid/resources/hyperliquid.md
- Trading/Exchange/hyperliquid/tests/__init__.py
- Trading/Exchange/hyperliquid_websocket_feed/__init__.py
- Trading/Exchange/hyperliquid_websocket_feed/hyperliquid_websocket.py
- Trading/Exchange/hyperliquid_websocket_feed/metadata.json
- Trading/Exchange/kucoin/kucoin_exchange.py
- Trading/Exchange/wavesexchange/wavesexchange_exchange.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1200
requires https://github.com/Drakkar-Software/OctoBot/pull/2925
> [Hyperliquid] add Hyperliquid tentacle
